# Generated by Django 4.2 on 2023-06-15 00:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasDeProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_categorias', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CentrosDeProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_interna', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('isla_de_produccion', models.CharField(max_length=40)),
                ('capacidad', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('tiempo_eficiencia', models.IntegerField()),
                ('eficiencia', models.IntegerField()),
                ('cantidad_operarios', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadosDeOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='IslasDeProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('ubicacion', models.CharField(max_length=40)),
                ('cantidad_operarios', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=20)),
                ('isla_de_produccion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_productos', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('packaging', models.CharField(max_length=40)),
                ('cantidad_siendo_producida', models.IntegerField()),
                ('cantidad_producida', models.IntegerField()),
                ('cantidad_a_producir', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operarios.categoriasdeproductos')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_orden', models.CharField(max_length=40)),
                ('cantidad_a_producir', models.IntegerField()),
                ('fecha_de_inicio', models.DateTimeField()),
                ('fecha_de_finalizacion', models.DateTimeField()),
                ('duracion', models.DurationField()),
                ('centro_de_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operarios.centrosdeproduccion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operarios.estadosdeorden')),
                ('productos_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operarios.productostemplate')),
            ],
        ),
    ]
